### PR TITLE
Adding Sniper Walk through

### PR DESCRIPTION
**Pull request by parteeksingh005**

### CODE REVIEW

**Comment by parteeksingh005** [comment]
I am from India already India flag is present in the countries folder. 
My HTB Nickname is parteeksingh

**Comment by OscarAkaElvis** [comment]
Ok but you also need to modify the Readme in order to add yourself.

**Comment by parteeksingh005** [comment]
> 
> 
> Ok but you also need to modify the Readme in order to add yourself.

Ok let me try i am new with git commands.

**Comment by parteeksingh005** [comment]
> 
> 
> Ok but you also need to modify the Readme in order to add yourself.

Anything else i have to make changes if required please let me know i'll check and do my best to update. 
Thanks

**Comment by parteeksingh005** [comment]
Hey the writeup is added in front page how can i add these into machines folder ?

**Pull request merged**
