### PR TITLE
Add Schooled writeup

### PR DESCRIPTION
**Pull request by HarshitRuwali**
the pdf is encrypted with the root hash/flag

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
Sorry, but we are not accepting anymore write ups of active machines. Read our policy: https://github.com/Hackplayers/hackthebox-writeups#important-notes-about-password-protection

**Comment by HarshitRuwali** [comment]
Ok. Just a thought, we can encrypt the writeup of the machines using their root password hash, found in the `/etc/shadow`. Or they are different too?

**Comment by OscarAkaElvis** [comment]
We know that. But we don't want to do that. The main goal of HTB about creating a dynamic flag system is to avoid the existing of a static string to solve the machine. Doing that, we are creating a static string to solve machines which is exactly what HTB crew don't want. That is the reason why we disagree to follow that method. We know other pages are doing it. We prefer to wait until it is retired to publish write-ups.

**Comment by HarshitRuwali** [comment]
Ok. Got your point, and totally support their view.

**Pull request closed without merging**
