### PR TITLE
Add misc challenge "Query"

### PR DESCRIPTION
**Pull request by apehex**
Hey there,

Here's a first sub, for the misc challenge Query:

- in English :heavy_check_mark:
- password protected :heavy_check_mark:
- I may be slow to respond in the following days, sorry in advance!
- updated the readme & filled my profile :heavy_check_mark:

(however I did not know where to put myself in the last table, so I chose a random line)

Cheers! :beers:

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
I have some comments before accepting this.

Why did you put "Loup solitaire" instead of "Solitaire Wolf" ? this is not free text to put whatever
Why didn't you add at the end of the list? If you are the last coming here, you should be at the end of the list of the "1 write up contributors".

**Comment by apehex** [comment]
It's just that solitaire is a french word so I just put "loup" instead of wolf on a whim.
I'll correct this in a moment, when I get to my personal space.

**Comment by apehex** [comment]
Well I looked at the commit log to see if there was a correlation between the table index & order of commits:
I saw that the last person on the list was not the last one to commit?

So I just put myself anywhere not knowing what to do.

Anyway, the right place was at the end then? I can correct that as-well np.

**Comment by apehex** [comment]
Voilà, sorry to have bothered you with insignificant stuff!

**Pull request merged**
