### PR TITLE
Updates Reminiscent Writeup

### PR DESCRIPTION
**Pull request by Karma47**

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
write up is ok, but the readme is conflicting. You need to do the changes over the latest version to solve the conflicts.

**Comment by Karma47** [comment]
Made changes to the latest read me file.

**Comment by OscarAkaElvis** [comment]
hhmm.... i think you are missing a right parenthesis on the link. Anyway, i merged another PR and i think you need to git pull again.

**Comment by Karma47** [comment]
Okay, thanks

**Comment by OscarAkaElvis** [comment]
What about this last commit? just adding a write up without link?

**Comment by Karma47** [comment]
I just added the link, i forgot to put the link there.

**Pull request merged**
