### PR TITLE
Adding writeups for Nest and OpenAdmin (retired, so no pw)

### PR DESCRIPTION
**Pull request by TheGroundZero**

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
Sorry. We are not accepting writeups for the machines with the new dynamic flag system. Traceback is one of them.

**Comment by TheGroundZero** [comment]
Please note that there are already writeups for Traceback present in this repository
image

**Comment by OscarAkaElvis** [comment]
Where?

https://github.com/Hackplayers/hackthebox-writeups/tree/master/machines/Traceback

Is empty. Maybe somebody accepted it as a mistake and then they were deleted. Otherwise, which flag to open them? we updated our policy on readme file . Sorry but not accepting anymore active machines since this change in hack the box.

If you still want to submit the rest of the write ups, delete them and i'll review them. Thanks.

**Comment by TheGroundZero** [comment]
My apologies, I was looking at my (outdated) fork
https://github.com/TheGroundZero/hackthebox-writeups/tree/master/machines/Traceback

I deleted the traceback writeup from the pull request and updated the README accordingly

**Pull request merged**
