### PR TITLE
Add writeups from FlatMarsSociet

### PR DESCRIPTION
**Pull request by TheGroundZero**
hackthebox-0ldisg0ld.pdf
hackthebox-art.pdf
hackthebox-bastion.pdf
hackthebox-blackhole.pdf
hackthebox-cartographer.pdf
hackthebox-crookedcrockford.pdf
hackthebox-easyphish.pdf
hackthebox-emdeefiveforlife.pdf
hackthebox-eternalloop.pdf
hackthebox-fs0ciety.pdf
hackthebox-fuzzy.pdf
hackthebox-iknowmag1k.pdf
hackthebox-inferno.pdf
hackthebox-infiltration.pdf
hackthebox-lernaean.pdf
hackthebox-longbottomslocker.pdf
hackthebox-m0rsarchive.pdf
hackthebox-misdirection.pdf
hackthebox-networked.pdf
hackthebox-writeup.pdf

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
Wow... I need some time to check'em all.

Anyway, about the readme... adding 20 write ups... your position is in number 5, not in number 25.... you need to modify the readme to set yourself upper in the ranking and modify the number of all that are under you substracting one to each one on their position.

**Review by TheGroundZero — COMMENTED** [review]
Updated README as requested

**Comment by OscarAkaElvis** [comment]
Ok thanks, let me some time to check all carefully.

**Comment by OscarAkaElvis** [comment]
Sorry for the delay. Finally I checked all the stuff. Checking your write ups...

Bastion is protected but is retired. It could be unprotected.
Inferno challenge is protected but is retired. It could be unprotected.
Lernaean challenge is protected but is retired. It could be unprotected.
Networked sequr has no password, and networked is protected ¿? It is retired so protected makes no sense... and why twice? And even with both... the names seems switched.

Anyway, I accepted it. These are "warnings", but nothing blocking.

**Comment by TheGroundZero** [comment]
Hi

Thanks for accepting the merge.

Networked was submitted first without password (3b27287), I removed it (482d1ce) and resubmitted with password (7880137).

I protected all PDFs by default.  
I can resubmit without PW once the boxes retire, like the ones you've mentioned now already.

**Pull request merged**
