### PR TITLE
Add emo

### PR DESCRIPTION
**Pull request by d4rkc0nd0r**
[emo.pdf](https://github.com/Hackplayers/hackthebox-writeups/files/6057339/emo.pdf)

Language : English
Status : Not retired
Challenge : emo (Forensics)

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
Hi, write up is ok, but you are missing the readme update. Read carefully the issue creation policy (text appearing while creating issue).

**Comment by d4rkc0nd0r** [comment]
I didn't get you. Can you please elaborate the issue?

**Comment by OscarAkaElvis** [comment]
on README file, there is a list of users with links to their hack the box profiles, flag image of their country, link to the write up, etc... you missed the part of updating the README file.

When you click on "new issue", read carefully the text appearing there, it explains about it.

**Comment by d4rkc0nd0r** [comment]
I'm very sorry for not noticing that. My apologies. I'll do that.

**Comment by OscarAkaElvis** [comment]
No problem. You can update the PR to add the modification of the readme file.

**Comment by d4rkc0nd0r** [comment]
Please do even add this crypto challenge (TwoForOne).

[TwoForOne.pdf](https://github.com/Hackplayers/hackthebox-writeups/files/6061094/TwoForOne.pdf)

lang: eng
status: not retired
challenge: TwoForOne

**Comment by d4rkc0nd0r** [comment]
#232

**Pull request merged**
