### PR TITLE
Create Jacker31-OpenAdmin.pdf

### PR DESCRIPTION
**Pull request by jacker31**
Hi Hackplayers team.

Greetings, i have attached the pdf file for the OpenAdmin writeup that I wish to submit.The Password is the root flag of OpenAdmin , do get it from me if you need it. I do not have Adobe acrobat or Foxit editor so i can't really add in extra protection measures such disabling the copy feature. Please get back to me if you guys have any feedback or question to ask. Cheers!

I emailed a copy of the pdf through the ymail address. The password is the root flag of this box.

Thank You,

Best Regards,
Jacker31

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
Hi, sorry but for some reason I can't see your pdf file. Anyway, the pdf is not enough. You must modify the readme file to add yourself there keeping the format.

**Comment by jacker31** [comment]
Hi, thanks for responding to me. I dont quite understand your readme file thingy, do you mind to explain more?

    On Monday, January 6, 2020, 9:32:25 PM GMT+8, Óscar Alfonso Díaz <notifications@github.com> wrote:  
 
 
Hi, sorry but for some reason I can't see your pdf file. Anyway, the pdf is not enough. You must modify the readme file to add yourself there keeping the format.

**Comment by OscarAkaElvis** [comment]
On the readme.md of this repo, there is a list of all the contributors. Link to their hackthebox profile, image, flag from his/her country, link to his/her team (if apply), etc... on the PR you need also to modify this readme.md file and add yourself with all the needed data.

So fork the repo, do the changes on the readme.md file, add your write up and then send the PR. I can close this if you want to start from zero again.

**Comment by jacker31** [comment]
Hi, I have uploaded to the file and fork-ed the readme.md file.

**Comment by OscarAkaElvis** [comment]
Sorry but I can't open the pdf... flag is not working as password. There must be something wrong.

**Comment by OscarAkaElvis** [comment]
I think the best is to close this ... perform a new PR with the pdf corrected and the modified readme.md , all in one.

**Pull request closed without merging**
