### PR TITLE
Add optimus prime writeup

### PR DESCRIPTION
**Pull request by hyperreality**

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
I've checked your script and seems ok except for an import.... `from math import gcd` should be `from fractions import gcd`. At least is how it worked for me. Tried even on python2. Do you want to review it?

**Comment by hyperreality** [comment]
@OscarAkaElvis Thanks for reviewing it.

Which version of Python are you using? On newer versions (> 3.7), Python issues a deprecation warning if you use `from fractions import gcd `, and says that the `gcd` function should be called from the `math` library now.

**Comment by OscarAkaElvis** [comment]
I tested it on python 3.7.55rc1 (latest on parrot security) and on python 2.7.16+.

**Comment by hyperreality** [comment]
That's strange, there's been deprecation warnings about using `fractions.gcd` since Python 3.5 apparently: https://github.com/scipy/scipy/issues/5874

**Comment by OscarAkaElvis** [comment]
Sorry but I've already tested also in a BlackArch Linux with same result.

Anyway, as you can see there are some conflicts on README file due major refactor changes @vmotos is doing, not your fault. I'll close this. Then wait until the refactor finishes and do the PR again. And check the script! 😄

**Comment by OscarAkaElvis** [comment]
Hey, changes on readme were finished. You can do PR safely again.

**Comment by hyperreality** [comment]
https://github.com/Hackplayers/hackthebox-writeups/pull/94

**Pull request closed without merging**
