### PR TITLE
Writeups for Frolic and OneTwoSeven(Updated)

### PR DESCRIPTION
**Pull request by mansoorr123**
>>Frolic Writeup:
https://github.com/mansoorr123/hackthebox-writeups/raw/9e16b0decf7b056fba40c8cf21b53f3b29fd0013/machines/Frolic/Mansoor-Frolic.pdf

>>OneTwoSevenWriteup:
https://github.com/mansoorr123/hackthebox-writeups/raw/9e16b0decf7b056fba40c8cf21b53f3b29fd0013/machines/OneTwoSeven/Mansoor-OneTwoSeven.pdf

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
The same song... please, update the readme with the links prior the acceptation of the PR.

**Comment by mansoorr123** [comment]
> The same song... please, update the readme with the links prior the acceptation of the PR.

Sorry but I am not getting which links you are asking me to quote
as I have already displayed links to my pdf file in my README.

**Comment by OscarAkaElvis** [comment]
Look at the write-up's README file. It shows all the contributing people with the avatar, the country, and links to the write-ups uploaded. Look:

image

You need also to update the README file linking your new write-ups.

**Comment by OscarAkaElvis** [comment]
good, only frolic link pending

**Pull request merged**
