### PR TITLE
corshine writeups

### PR DESCRIPTION
**Pull request by rhovelz**

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
Write up is ok, but you didn't modify the readme file to put yourself there with the links.

**Comment by rhovelz** [comment]
How do I do that? can you elaborate more?

**Comment by OscarAkaElvis** [comment]
All is explained at the PR template (the text in the comments when you are going to perform a Pull Request using the button from this github repo).

Remember in addition to add the write-up to update the Readme file keeping the format. If you are already there, just add the link to the new write-up. If you are new, add your HTB nickname, your country, the image of your avatar to images dir, the image of your country flag to images/countries and add the link to the new write-up you wan to add

There are three categories of contributors based on the number of write-ups you submitted. If you change from category be pretty sure of updating correctly the tables and re-ordering the "ranking" if needed

**Comment by rhovelz** [comment]
Oh okay, got it, so do I need to do pr again?

**Comment by OscarAkaElvis** [comment]
You can add more commits to the PR... if you prefer I can close this PR and you can do a new PR with all the needed stuff.

**Comment by rhovelz** [comment]
Sure just close it sir, Im gonna do new PR, thank you in advance.

**Comment by rhovelz** [comment]
Done edited readme @OscarAkaElvis

**Pull request merged**
